services:

    _defaults:
        autoconfigure: true
        autowire: true

        bind:

    App\:
        resource: '../../src/'
        exclude:
            - '../../src/*/Domain/Entity/'
            - '../../src/Framework/Domain/'
            - '../../src/Framework/Application/'
