monolog:
    channels:
        - music
        - deprecation
        - event
        - doctrine
        - php

    handlers:
        music:
            type: fingers_crossed
            handler: elk
            channels: ['music']
        deprecation:
            type: fingers_crossed
            handler: elk
            level: debug
            channels: ['deprecation']
        event:
            type: fingers_crossed
            handler: elk
            level: debug
            channels: ['event']
        doctrine:
            type: fingers_crossed
            handler: elk
            level: debug
            channels: ['doctrine']
        console:
            type: fingers_crossed
            handler: elk
            level: debug
            channels: ['console']
        php:
            type: fingers_crossed
            handler: elk
            level: debug
            channels: ['php']
        elk:
            type: socket
            connection_string: "tcp://logstash:5000"
            formatter: monolog.formatter.json
