name: music

x-extra_hosts: &x-extra_hosts
  extra_hosts:
    - "host.docker.internal:host-gateway"

services:
  frankenphp:
    <<: *x-extra_hosts
    container_name: music_frankenphp
    restart: 'unless-stopped'
    build:
      # Контекст для Dockerfile и для build секции
      context: '..'
      dockerfile: './docker/frankenphp/Dockerfile'
    working_dir: '/app/'
    volumes:
      - './../:/app/'
      - './frankenphp/Caddyfile:/etc/frankenphp/Caddyfile:ro'
      - './frankenphp/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro'
    env_file:
      - './../.env'

networks:
  default:
    driver: bridge
