name: music

x-extra_hosts: &x-extra_hosts
  extra_hosts:
    - "host.docker.internal:host-gateway"

services:
  frankenphp:
    <<: *x-extra_hosts
    container_name: music
    restart: 'unless-stopped'
    build:
      # Контекст для Dockerfile и для build секции
      context: '..'
      dockerfile: './docker/frankenphp/Dockerfile'
    working_dir: '/app/'
    volumes:
      # for dev only
#      - './../:/app/'
      - './../load_music:/app/load_music'
      - './frankenphp/Caddyfile:/etc/frankenphp/Caddyfile:ro'
      - './frankenphp/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro'
    dns:
      - 1.1.1.1   # Cloudflare
      - 8.8.8.8   # Google

  music_memcached:
    container_name: music_memcached
    build:
      context: './memcached'
      dockerfile: 'Dockerfile'
    restart: unless-stopped
    volumes:
      - './memcached/volumes/:/var/log/memcached/'

  elasticsearch:
    build: './elasticsearch'
    container_name: music_elasticsearch
    volumes:
      - './elasticsearch/volumes:/usr/share/elasticsearch/data'
    restart: unless-stopped

  logstash:
    build: './logstash'
    container_name: music_logstash
    volumes:
      - './logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf'
    depends_on:
      - elasticsearch
    restart: unless-stopped

  kibana:
    build: './kibana'
    container_name: music_kibana
    depends_on:
      - elasticsearch
    restart: unless-stopped

networks:
  default:
    driver: bridge
