parameters:
    app.music_service.music_extensions:
        - mp3
        - flac
        - wav
        - aac
        - m4a
        - ogg
        - wma
        - alac
        - aiff
        - aif
        - aifc
        - ape
        - dsf
        - dff
        - amr
        - ac3
        - dts
        - ra
        - rm
        - au
        - snd
        - caf
        - weba
        - mid
        - midi
        - opus
        - mp2
        - mp1
        - mpc
        - aup
        - aup3
        - als
        - logicx
        - ptf
        - sesx
        - sf2
        - mod
        - xm
        - it
        - s3m
        - raw
        - pcm
